### PR TITLE
fix(culture): fixing an issue where the query string is generated incorrectly in different cultures

### PR DESCRIPTION
**Pull request by JustinCanton**

### CODE REVIEW

**Comment by vanenshi** [comment]
Hi @JustinCanton, is there anything I need to do?

**Comment by JustinCanton** [comment]
@vanenshi, if you want, you can review the code if you want, just to make sure it does what you need. Other than that, I think you are fine.

**Comment by JustinCanton** [comment]
@vanenshi, the code has been merged and a 1.2.1 nuget package has been generated. Let me know if you run into any other issues.

**Comment by vanenshi** [comment]
Yes @JustinCanton 
I just tested it out, and everything works as expected. Thank you for the effort

**Pull request merged**
