### PR TITLE
Include Score information inside Here.com response as missing

### PR DESCRIPTION
**Pull request by caspertwo**

### CODE REVIEW

**Review by michaelcontento — APPROVED** [review]
looks good to me

**Review by JustinCanton — CHANGES_REQUESTED** [review]

**Comment by JustinCanton** [comment]
I am not sure why I didn't add this in the first place. But thank you for the update.

**Comment by caspertwo** [comment]
Cool, thanks a lot! Any chance on releasing the `develop` changes soon? Didn't want to mess with the branch strategy here and that's why the PR was against `develop` and not `master` directly 😅

**Comment by caspertwo** [comment]
Great! Thanks a lot & keep up the good work! 👍

**Pull request merged**
